### ISSUE TITLE
some trouble while "MAKE"

### ISSUE THREAD

**Issue by YD1RUH** [ccmolik/aprsweb#1]
go-bindata -pkg bindata -o bindata/bindata.go -fs -prefix "static/" assets/...
go test -v ./...
cmd/aprsweb/aprsweb.go:11:9: cannot find package "github.com/ccmolik/aprsweb-proto/rpc/aprsweb" in any of:
        /usr/lib/go-1.13/src/github.com/ccmolik/aprsweb-proto/rpc/aprsweb (from $GOROOT)
        /home/waf/go/src/github.com/ccmolik/aprsweb-proto/rpc/aprsweb (from $GOPATH)
cmd/aprsweb/aprsweb.go:12:2: cannot find package "github.com/ccmolik/aprsweb/bindata" in any of:
        /usr/lib/go-1.13/src/github.com/ccmolik/aprsweb/bindata (from $GOROOT)
        /home/waf/go/src/github.com/ccmolik/aprsweb/bindata (from $GOPATH)
cmd/aprsweb/aprsweb.go:13:2: cannot find package "github.com/ccmolik/aprsweb/internal/aprswebtwirp" in any of:
        /usr/lib/go-1.13/src/github.com/ccmolik/aprsweb/internal/aprswebtwirp (from $GOROOT)
        /home/waf/go/src/github.com/ccmolik/aprsweb/internal/aprswebtwirp (from $GOPATH)
cmd/aprsweb/aprsweb.go:14:2: cannot find package "github.com/ccmolik/aprsweb/internal/packethandler" in any of:
        /usr/lib/go-1.13/src/github.com/ccmolik/aprsweb/internal/packethandler (from $GOROOT)
        /home/waf/go/src/github.com/ccmolik/aprsweb/internal/packethandler (from $GOPATH)
cmd/aprsweb/aprsweb.go:15:2: cannot find package "github.com/ccmolik/aprsweb/internal/packetstore" in any of:
        /usr/lib/go-1.13/src/github.com/ccmolik/aprsweb/internal/packetstore (from $GOROOT)
        /home/waf/go/src/github.com/ccmolik/aprsweb/internal/packetstore (from $GOPATH)
internal/packethandler/packethandler.go:15:2: cannot find package "github.com/ccmolik/aprsweb/packet" in any of:
        /usr/lib/go-1.13/src/github.com/ccmolik/aprsweb/packet (from $GOROOT)
        /home/waf/go/src/github.com/ccmolik/aprsweb/packet (from $GOPATH)
packet/packet.go:12:2: cannot find package "github.com/shopspring/decimal" in any of:
        /usr/lib/go-1.13/src/github.com/shopspring/decimal (from $GOROOT)
        /home/waf/go/src/github.com/shopspring/decimal (from $GOPATH)
make: *** [Makefile:18: test] Error 1

**Comment by ccmolik** [comment]
Thanks for your interest in aprsweb!

After taking a look, I noticed that the `Makefile` doesn't seem to call installs for some of the dependent repo stuff (indeed, it doesn't actually call `go get` to grab the dependencies.)

I've created PR #2 to set up Go Modules, and that SHOULD fix things for you.

I noticed you're running Go 1.13. This patch fixes things for me on Go 1.15; would you be so kind as to pull the `go-mod` branch and try running `make` again?

Sorry for the inconvenience.
